kind: ClustersConfiguration
apiVersion: vab.mia-platform.eu/v1alpha1
name: multicluster
spec:
  modules:
    ingress/traefik/base:
      version: v0.0.1
    security/cert-manager/base:
      version: v0.0.1
    scheduling/kube-green/base:
      version: v0.0.0
    observability/logging-operator/base:
      version: v0.0.0
    observability/prometheus-operator/base:
      version: v0.0.1
    security/rbac-manager/base:
      version: v0.0.0
    security/kyverno/base:
      version: v0.0.1
  addOns:
    cert-manager/kube-green-webhook:
      version: v0.0.1
    cert-manager/prometheus-operator-webhook:
      version: v0.0.1
    logging-operator/logging-stack:
      version: v0.0.1
    prometheus-operator/monitoring-stack:
      version: v0.0.1
    prometheus-operator/cert-manager:
      version: v0.0.1
    prometheus-operator/kube-green:
      version: v0.0.1
    prometheus-operator/logging-operator:
      version: v0.0.1
    prometheus-operator/logging-stack:
      version: v0.0.1
    prometheus-operator/rbac-manager:
      version: v0.0.1
    prometheus-operator/traefik:
      version: v0.0.2
  groups:
    - name: clusters-group
      clusters:
        - name: kind-cluster
          context: kind-cluster
        - name: gke-cluster
          context: gke-cluster
          modules:
            ingress/traefik/base:
              disable: true
            ingress/traefik/gke:
              version: v0.0.1
