run:
  deadline: 10m

linters:
  enable:
    - asciicheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - misspell
    - revive
    - tagliatelle
    - unconvert
    - whitespace
  disable: # disabled check for https://github.com/golangci/golangci-lint/issues/2649, track it for re enabled them
    - bodyclose
    - structcheck
    - unparam
linters-settings:
  gofmt:
    simplify: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        yaml: camel
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: zz_generated
      linters:
        - goimports
