run:
  deadline: 10m

linters:
  enable:
    - asciicheck
    - bodyclose
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - misspell
    - revive
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  gofmt:
    simplify: true
  goconst:
    ignore-tests: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        yaml: camel
  unparam:
    check-exported: false
  gomnd:
    # Values always ignored: "1", "1.0", "0" and "0.0"
    ignored-numbers:
      - "5" # used for alternative logger level
      - "10" # used for alternative logger level

issues:
  exclude-rules:
    - path: zz_generated
      linters:
        - goimports
