name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
env:
  GO_VERSION: 1.18.5
  GO_CACHE: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Set golangci-lint cache key
        id: create-sha
        run: |
          echo "GOLANGCILINT_SHA=$(make lintgo-dep --dry-run | sha256sum - | awk '{ print $1 }')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ./tools/bin
          key: ${{ runner.os }}-go-${{ env.GOLANGCILINT_SHA }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make lint MODE="github-actions"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: ${{ env.GO_CACHE }}
      - run: make build-all
      - run: make test-coverage
