name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint MODE="github-actions"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build-all
      - run: make test-coverage
