name: Install golang version

on:
  workflow_call:

jobs:
  install_golang:
    name: Install golang 1.18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
          cache: true
